language: objective-c

before_script:
    - brew update

script:
  - pod install
  - xcodebuild -workspace PocketMovies.xcworkspace -scheme "PocketMovies" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.4' test

branches:
  only:
    - develop-mvp-architecture
